##   Copyright 2021 Orange
##
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##
##       http://www.apache.org/licenses/LICENSE-2.0
##
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.

## This Dockerfile is based on salt-netdev-docker's Dockerfile (https://github.com/mirceaulinic/salt-netdev-docker/blob/master/Dockerfile-proxy)
## Changes done:
## - Added python and network dependencies
## - Changed the version of Salt to be installed
## - Added pyyaml
## - Added pyinotify

FROM debian:stretch

ENV DEBIAN_FRONTEND noninteractive

## Install min deps
RUN apt-get update \
  && apt-get install -y apt-utils \
  && apt-get install -y wget \
  && apt-get install -y gnupg \
  && apt-get install -y git \
  && apt-get install -y iputils-ping \
  && apt-get install -y nano \
  && apt-get install -y htop \
  && apt-get install -y python \
  && apt-get install -y python-pip \
  && apt-get install -y net-tools \
  && apt-get install -y tcpdump \
  && rm -rf /var/lib/apt/lists/*

## Setup sources for Jessie backports and SaltStack repo
RUN echo 'deb http://httpredir.debian.org/debian stretch-backports main' >> /etc/apt/sources.list \
    && echo 'deb http://repo.saltstack.com/apt/debian/9/amd64/archive/2019.2.0/ stretch main' >> /etc/apt/sources.list.d/saltstack.list \
    && wget -O - https://repo.saltstack.com/apt/debian/9/amd64/archive/2019.2.0/SALTSTACK-GPG-KEY.pub | apt-key add - \
    && apt-get update

## Install backports
RUN apt-get install -y python-zmq

## Install the Salt Minion
RUN apt-get install -y salt-minion=2019.2.0+ds-1

## Install other dependencies
RUN pip install pyinotify

## Update pyyaml
RUN pip install --upgrade pyyaml

ADD ./minion_files/minion /etc/salt/minion

# Add Run File
ADD run-minion.sh /usr/local/bin/run.sh
RUN chmod +x /usr/local/bin/run.sh

# Ports
EXPOSE 4505 4506

# Run Command
CMD "/usr/local/bin/run.sh"
